### PR TITLE
use production rand 0.5 release

### PR DESCRIPTION
**Pull request by mcginty**
0.5 is finally out of prerelease purgatory 🎉

### CODE REVIEW

**Comment by canndrew** [comment]
Is there anything blocking getting this merged? I can't build with dalek at the moment because the old rand version causes all kinds of problems.

**Comment by nbaksalyar** [comment]
`rand` dependencies in many libs get broken without this change.
@isislovecruft could you please merge this and release `x25519-dalek 0.3.0`?

**Comment by kpcyrd** [comment]
Any updates on this? This currently forces me to use an outdated version of snow, see https://github.com/mcginty/snow/pull/29

**Comment by isislovecruft** [comment]
Hi! I'm sorry, I totally missed this in all the noise. I'll merge and put out a point release today.

**Pull request merged**
