### PR TITLE
Upgrade rand dependency

### PR DESCRIPTION
**Pull request by chmln**

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Ping, any chance this getting merged? @hdevalence

**Comment by hdevalence** [comment]
Hi there, I've been doing maintenance catchup this afternoon but I think I won't be able to get to looking at this one today.  In general I think we want to align the `rand_core` dependency of `x25519-dalek` with that of `curve25519-dalek`, which is stuck due to semver requirements on the major version.  However, it turns out that we got the Serde implementation wrong (https://github.com/dalek-cryptography/curve25519-dalek/issues/265#issuecomment-536132620) so I would like to do a `2.0.0` release, and that may make it possible to update.

**Comment by exrook** [comment]
Any progress on this now that `curve25519-dalek` 2.0 is out?

**Comment by hdevalence** [comment]
Yup, this is unblocked now, I'm expecting that there will be a new x25519 version with new `rand` this week.

**Comment by DebugSteven** [comment]
Thank you for writing this patch to update the rand_core version.
There were a couple of changes in order to get this work merged in and it has been incorporated into #52 with attribution. Thank you for your contribution!

**Pull request closed without merging**
